### PR TITLE
Added dynamic search option in sidebar component

### PR DESCRIPTION
**Pull request by DiabolusGX**
- Added props in sidebar to accept optional title, placeholder and boolean for displaying text field
- Added `allThreads` state to track and search threads from originally all available threads
- Added optional `onChange` handler for input field to execute a function in threads <- sidebar <- input field change event
- Changed `xl:mb-16 2xl:mb-32` in Sidebar.tsx to line 33 to make searchbar look better (change it according to you later)

### CODE REVIEW

**Comment by AviusX** [comment]
We do not need a search functionality right now. Especially because it destroys the UI. If a search result returns only a single thread, this is what happens to the UI right now-
image

Apart from this, `allThreads` is not required as a state. If the UI renders `threads` instead of `allThreads`, then `allThreads` can be a regular array instead of being a state. That's just a tip for the future. Since the search functionality currently breaks the UI I'm not going to implement it right now. This could be fixed with a max-height class on the `ThreadCard`s but another problem is that if the search functionality is implemented in the sidebar then mobile users cannot use it at all. Which is why I will reimplement search functionality completely later.

**Comment by DiabolusGX** [comment]
Then add the search bar on top of threads list and put max height on ThreadCards?
Cuz there has to be a search option.

**Comment by DiabolusGX** [comment]
and I considered making `allThreads` an array but It has to be assigned as null first (outside any other function) and then add data inside `useEffect` and It was causing unexpected errors so I left it as state, any downsides of making it state?

**Comment by AviusX** [comment]
Closing after further discussion over call.

**Pull request closed without merging**
